# Generated by Django 5.0.1 on 2024-02-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Для адресной строки'),
        ),
    ]
