# Generated by Django 5.0.1 on 2024-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_like_count_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(blank=True, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], max_length=20, verbose_name='Статус'),
        ),
    ]
