# Generated by Django 5.0.1 on 2024-02-12 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время публикации'),
        ),
    ]
